config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "lists#index"
  resources :lists, only: [:new, :create, :show, :destroy] do
    resources :bookmarks, only: [ :new, :create]
  end
  resources :bookmarks, only: [ :destroy ]
  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :list_image

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  def new
    @bookmark = Bookmark.new

  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.movie = @movie
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: "bookmark was successfully created."
    else
      render :new, status: :unprocessable_entity
    end


  end


  def update
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end


  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show
    # @movies = @list.movies
    @bookmarks = @list.bookmarks
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      @list.save
      redirect_to @list, notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      redirect_to root, notice: "list was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to root_url, notice: "list was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :phone_number, :address, :category, :list_image)
    end
  end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_to_with_icon(text, path, classes)
    form_tag path, :method => :post do
      button_tag(classes) do
        raw text
      end
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="card-movie">
  <img src="<%= bookmark.movie.poster_url%>" />
  <div class="card-movie-infos">
    <div>
      <h2><%= bookmark.movie.title %> - <i class="fa-regular fa-star color-yellow"></i> <%= bookmark.movie.rating %></h2>
      <p><%= bookmark.movie.overview %></p>

      <div class="d-flex justify-content-between mt-2 comment">
        <div>
          <p> <strong>Comment: </strong><%= bookmark.comment %></p>
        </div>
        <div class = "d-flex align-content-end">
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-decoration-none text-danger mt-auto" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [:list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Movie#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>
<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/update.html.erb
<h1>Bookmarks#update</h1>
<p>Find me in app/views/bookmarks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render partial: 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :list_image, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.list_image.attached? ? (cl_image_path list.list_image.key, height: 300, crop: :fill) : image_url("default-bg.jpg") %>)">
  <a href="/lists/<%= list.id %>"><%= list.name %></a>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path("default-bg.jpg") %>);">
  <div class="container">
    <h1>My <strong>movie</strong> lists</strong>!</h1>
    <p>Manage your backlog of movies</p>
    <%= link_to "New list", new_list_path, class: "btn btn-primary m-8  " %>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<p style="color: green"><%= notice %></p>
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12">

     <h1 class="text-center">My Lists</h1>
    </div>
  </div>
</div>

<div class="container mt-3">
 <div class="grid">
    <%# <div id="lists"> %>
      <% @lists.each do |list| %>
          <%= render list %>
      <% end %>
    <%# </div> %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= @list.list_image.attached? ? (cl_image_path @list.list_image.key, height: 800, width: 1200, crop: :fill) : image_path("default-bg.jpg") %>);">
  <div class="container">
    <h1>My <strong><%= @list.name %></strong> list</strong>!</h1>
    <%# <p>Change your life and learn to code at one of our campuses around the world.</p> %>
    <%= link_to "Add a movie", "../lists/#{@list.id}/bookmarks/new", class: "btn btn-primary mt-3" %>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>
<div class="container mt-3">

 <div class="grid">
    <%# <div id="lists"> %>
      <% @bookmarks.each do |bookmark| %>
          <%= render bookmark %>
      <% end %>

    <%# </div> %>
  </div>
  <%= button_to "Delete List", @list, method: :delete, class: "btn btn-warning text-color-white mt-3" %>
</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "pop-corn.png", alt: "popcorn", width: 8 %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/lists">My Lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">New List</a>
          </li>
          <%# <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li> %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>